name: Update Dependency Graph

on:
  pull_request:
    types:
      - closed
    branches: [ "master", "development" ]
    
env:
  NODE_VERSION: '16.14.2'

jobs:
  if_merged:
    name: Install packages and update dependency graph
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
      
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install
      run: |
        npm install
        npm run install-graphviz-linux
        
    - name: Generate
      run: npm run depcruise
      
  commit_push:
    name: Commit and push changes
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event.pull_request.merged == true
    run: |
        git config --global user.email "shea.wow@hotmail.com"
        git config --global user.name Shea Dougherty-Gill
        git commit -a -m "Dependency Graph ${{ vars.IGNORE_DEPLOY }}"
        git push