# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - testcollabfe

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '16.14.2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build-dev --if-present
          npm run test --if-present -- --watch=false --browsers=ChromeHeadless

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'testcollabfe'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_64082DF3F72B4588A9ACB776CEAD3B24 }}
          package: ./dist/gccollab-frontend
